osx_image: xcode 10.2
language: swift
osx_image: xcode10

before_install:
  - gem install cocoapods -v '0.32.1'

script:
    - xcodebuild clean test -workspace SelfCare.xcworkspace -scheme SelfCare -destination "platform=iOS Simulator, name=iPhone Xs Max, OS=12.0"

after_success:

# safelist
branches:
  only:
  - master
  - Development
