name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line scriptf\
      run: echo SelfCare has passed!
        echo Add other actions to build,
        echo test, and deploy your project.
